rackn/digitalrebar-deploy

compose/docker-compose-common.yml

We only really want a subset of ports exposed on the host running the
containers:
3000 (for the Crowbar UI and API),
8500 (so we can access the Consul UI),
5601 (so we can access Kibana), and
8080 (so we can access cadvisor).
Everything else is cluster internal, and does not need to be exposed on
the host.

Stop exposing extra ports on the host.

---

Vagrantfile
vagrant.yml

permissions issues made this not always work.  does not matter at all if you only use vagrant.

tweaking vagrant to avoid collisions w/ local compose

---

compose/docker-compose.yml

This was causing bringup failures at Mesosphere, but not in my local env for some reason.

Link from DHCP to Forwarder container was missing.

---

compose/common.env
compose/config-dir/postgres/initdb.d/01-rebar-user.sh
compose/config-dir/postgres/initdb.d/02-goiardi-user.sh
compose/docker-compose-common.yml
compose/docker-compose-no-forwarder.yml
compose/docker-compose.yml

Allow for the services to be internally provided (service name has internal- and is exposed by the forwarder) or externally provided (ports are mapped to the host).  The system watches the FORWARDER_IP and EXTERNAL_IP to determine route changes and service names.
By default, the system assumes that FORWARDER_IP and EXTERNAL_IP are the same and that a FORWARDER will be created.
A new compose file is added, docker-compose-no-forwarder.yml, that assumes that FORWARDER_IP is not set and EXTERNAL_IP is an IP on the host.  It will NOT run a forwarder and expose the ports through the host.
This turns off some logging and cleans up the compose files.

Forwarder dhcp choice

---

compose/yaml_templates/provisioner.yml

upset with the host based networking and links.

DHCP doesn't need links and some versions of compose gets

---

LICENSE.rst

This license expresses RackN intent around the deploy components we've added to Digital Rebar.  It will be copied to other RackN extensions.

add correct License information

---

tasks/compose.yml

Use the shared join scripts with the rest of the tools.

Don't need to share the key anymore.

---

tasks/docker-linux.yml

Fixed issue with install trying to use the centos docker-selinux package instead of the Docker repo's selinux package (docker-engine-selinux), this fixes the install from failing due to package conflicts.

Fixed selinux installer to use Docker's repo instead of centos

---

compose/yaml_templates/base.yml

in host mode.  We can bind it to localhost to
have some security.

Consul has to be exposed on the host for DHCP

---

compose/config-dir/consul/client-default.json
compose/config-dir/consul/server-default.json
compose/docker-compose-common.yml
compose/init_files.sh
compose/yaml_templates/base.yml
compose/yaml_templates/provisioner.yml

This modifies the templates and init_files.sh to allow the Consul
container to always run in host mode.  It tries to be smart about
telling the Consul server what address on the host to advertise to the
other consuls, and complains and dies loudly if it cannot pick one.

Have Consul always run in host mode.

---

compose/docker-compose-common.yml

The data that Consul and Postgres store need to persist.  We will store
them in volumes to enable that persistence.

Store critical databases in mounted volumes.

---

tasks/compose.yml

was trying local install and Ansible failed because I had an RSA key already.
This was able to get it past that step

skip the RSA key create if it already exists

---

tasks/base-ubuntu1510.yml
tasks/base.yml
tasks/compose.yml
tasks/docker-linux.yml

Using 15.10 had different package (ruby-dev) than the current 14.04 stable list.

account for prereq package differences in new Debian versions

---

tasks/compose.yml

Skipping ISOs saves a lot of time if you are not using the provisioner.
Also, give some more debug info before waiting for UI to come up.

skip ISOs unless using provisioner, debug info for final test

---

Vagrantfile
group_vars/all.yml
tasks/base-centos.yml
tasks/base-debian-7.yml
tasks/base-debian-8.yml
tasks/base-ubuntu1404.yml
tasks/base-ubuntu1510.yml
tasks/compose.yml

This includes changes to Vagrant that assumes we don't want to setup provisioning hosts w/ Vagrant - we've learned that metal provisioning from Vagrant is very complex because of networking configuration.

Don't do extra work if we don't need a provisioner

---

workloads/docker-swarm.sh
workloads/kubernetes.sh
workloads/os.map
workloads/test_os_lookup.sh
workloads/wl-lib.sh

standard os name to lookup the right string for that
provider type.  Add a test script.
Also allow for existing admin nodes not have to wait
for convergence.

Add an OS map to the script tools.  This will pass a

---

tasks/compose.yml

the ipaddr command requires ansible > 1.9.  it is the only item that requires that.
skip the site up test if we're not using the right version so we don't scare users
also, the .netrc transfer is handy but we can just skip errors instead of the complex way it was being done before.
shorten timeouts now that we know why it was failing.

cleanup scripts for generic use case 

---

Vagrantfile

Changed the approach for Vagrant Admin (base) to match simple instructions.  This new approach does NOT require cloning the repo locally - you can run it from the Vagrant file alone.
Vagrant admin is only for quick trails - devs should use docker admin tooling.
The node# now respects the REBAR_ENDPOINT if set.
Also, added some helpful information in the header.

Vagrant working for base

---

workloads/wl-lib.sh

this is really handy for development because we can add/remove nodes from the UI and it creates activity on demand.
Thank you @galthaus for the add-provider method.

add debug provider for use with new add-provider.sh

---

containers/provisioner/entrypoint.d/40-get-sledgehammer.sh
containers/provisioner/entrypoint.d/42-start-services.sh
containers/provisioner/entrypoint.d/45-bind-provisioner-service.sh
containers/provisioner/entrypoint.d/50-find-supported-operating-systems.sh
containers/provisioner/entrypoint.d/60-bind-services.sh
containers/provisioner/entrypoint.d/80-register-consul-services.sh
containers/provisioner/start-up.sh

This shifts responsibility for discovering installable operating systems
from the provisioner-base-images role into one of the startup scripts
for the provisioner container.

Make provisioner container discover installable oses

---

run-in-docean.sh
workloads/wl-lib.sh

Requires Tugboat CLI to be installed.
This is a first pass but handy for creating new Digital Ocean servers.
Assumes that you have done a tugboat authorize to add api keys

add quick path for digital ocean servers

---

workloads/wl-init.sh

on a completely new system, we need to have an SSH key

make sure we have an ssh key

---

.gitignore
compose/docker-compose-common.yml
compose/init_files.sh
containers/rebar-api/entrypoint.d/26-build-config-file.sh
containers/rebar-api/entrypoint.d/27-bind-rebar_api-service.sh
containers/rebar-api/entrypoint.d/32-wait-for-services.sh
containers/rebar-api/entrypoint.d/34-bootstrap-rebar.sh

This patch updates init_files.sh to pass a list of services that
rebar_api should wait to be bound in the system deployment before
letting the annealer run.  It also rearranges the startup scrupt
ordering to ensure that we only run initial bootstrap tasks after all
the services we require are present and accouted for.

Make rebar_api startup a bit smarter.

---

run-in-google.sh

I don't know whether this is unique to my GCE environment, but whenever I create a new VM, I get a load of keys put into /root/authorized_keys relating to the SSH keys set up on my GCE project.  A lot of these are configured to not allow root login - the key begins with 
"no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10" ssh-rsa AAAA....."
Because the key being used by Rebar is one of these, rebar fails as it gets unexpected output to its commands.
This PR, which works for me, removes any lines in the authorized_keys file which have this command.  The deploy scripts still add the appropriate key manually, so deleting these keys doesn't seem to cause a problem.
TBH - I don't know …

Make sure any keys that disable root login are removed from host

---

tasks/base-ubuntu1404.yml

I've found the "Update Python" step can take a long time on a newly provisioned master (I guess because its actually doing a full apt-get upgrade of everything?).  Maybe a complete fix is to _just_ update Python, but in the meantime a warning that this step can be slow would be helpful.

Updating Python step can be very slow, so warn users

---

containers/cloudwrap/Dockerfile
containers/cloudwrap/cloudwrap/api.rb
containers/cloudwrap/cloudwrap/common.rb
containers/cloudwrap/cloudwrap/openstack.rb
containers/cloudwrap/cloudwrap/waiter.rb
workloads/wl-lib.sh

OpenStack Provider Interface (based on DreamHost)
This pull includes the initial working OpenStack Provider.  It was developed against the Dreamhost Cloud.  
It uses the python OpenStack CLI instead of trying to talk to the API directly.  This supposes that that CLI will be better supported than direct API calls or Fog.  That is included in the Dockerbuild file and will require an update to the Cloudwrap container.
Since this only tested one cloud, there will be changes as we add more cloud instances.  However, I've made attempts to handle variation in images & flavors between clouds.
The OpenStack code is wrapped in a dedicated class to minimize complexity.  Some refactoring of the Waiter.rb was needed to mix code w/ Packet.
Requires DigitalRebar Core #1128

OpenStack Provider Interface (based on DreamHost) 

---

containers/cloudwrap/Dockerfile
containers/cloudwrap/cloudwrap/openstack.rb
containers/cloudwrap/cloudwrap/waiter.rb

To create networks with the OpenStack CLI, I had to include the GUIDs that are available only from the Neutron CLI.  This update includes adding the Neutron CLI to the apt-get instructions.
Then I wrapped neutron in a generic way for the networks list.
At this time, it's hard coded to use public and private.  It also requires you to have both networks.  
Will fix that in the next pull.

add network awareness for OpenStack provider using neutron CLI

---

containers/cloudwrap/cloudwrap/openstack.rb
containers/cloudwrap/cloudwrap/waiter.rb

Found issue w/ net elimination script - this handles when there is >1 subnet.
Also, provide a little more feedback (0s in IP) if we can't ssh into a system.  This happens when the IPs given are not public.

continue to tweak based on cloud behaviors

---

.gitignore
tasks/compose.yml

instead of just pushing ISOs, it makes sense to allow users to pre-cache their whole TFTPboot path for local installs.  This simplifies the upload and creates the working directory.

allow users to pre-cache tftpboot locally and then upload

---

fast/kubernetes/Dockerfile

This is WIP - it seems to be having trouble w/ AWS keygen.  
To use, docker build fast/kubernetes
Then docker run -it -v ~/.dr_info:/root/.dr_info $IMAGE
This is "just work" if you have created a .dr_info file.

all in one dockerfile to install kubernetes from docker run

---

compose/docker-compose-common.yml
workloads/os.map

Let the rebar_api have access to the file cache so
that ansible playbooks can cache files in it if need.

Update the centos7 os.map to latest centos7 images

---

compose/init_files.sh
containers/base/docker-entrypoint.sh
containers/dns/entrypoint.d/50-register-and-start-bind.sh
containers/provisioner/entrypoint.d/60-bind-services.sh
containers/provisioner/entrypoint.d/80-register-consul-services.sh
containers/rebar-api/entrypoint.d/22-set-entrypoint-for-everything-else.sh
containers/rebar-api/entrypoint.d/23-wait-for-api-to-start.sh
containers/rebar-api/entrypoint.d/24-build-initial-machine-keys.sh
containers/rebar-api/entrypoint.d/27-bind-rebar_api-service.sh
containers/rebar-dhcp/entrypoint.d/20-start-dhcp.sh
containers/rebar-dhcp/entrypoint.d/40-update-consul.sh
containers/rebar-rev-proxy/entrypoint.d/27-start-services.sh
containers/rebar-rev-proxy/rebar-rev-proxy/digest.go
containers/rebar-rev-proxy/rebar-rev-proxy/registry.go

Create a make_revproxied_service helper in docker-entrypoint, and fix
everything up to use it to register services that should be exposed via
the revproxy instead of the forwarder.

Rework how we register revproxy services -- REVIEW ONLY

---

compose/common.env

Always rebuild bower, because we don't have all the components
