rackn/digitalrebar-deploy

compose.yml
install_ansible.md
tasks/centos07-base.yml
tasks/docker.yml

Merge the compose system into a single playbook that
can choose os.

Create centos7 support for base system to run containers

---

compose.yml
run-in-packet.sh

Use compose.yml in run-in-packet.sh

Fix botch includes

---

compose.yml
tasks/centos07-base.yml
tasks/ubuntu1404-base.yml

Make sure wget is installed and actually

---

Vagrantfile
compose/setup.sh
compose/workload.sh

1) if dr core already exists, just pull latest
2) you can setup workloads from the setup command by adding them to the command line

make it easier to install workloads during setup

---

Vagrantfile
compose.yml
run-in-packet.sh
vagrant.yml

WIP but better than what's there so I wanted to get it out there.
Plus, some minor items to the general compose that @galthaus thought would be useful to share.

Working on Vagrant Install

---

run-in-packet.sh

make it easier to tell how old servers are in Packet.

add time stamp to naming

---

compose/config-dir/bind/named.conf

Put the old bind 9.4 functionality back with regard

---

.gitignore
.rsync-filter
Vagrantfile
install_vagrant.md
vagrant.yml

Addresses the problem by ignoring files that we did not want anyway!

Fixes for Vagrant (was having permissions issues w/ Ansible Sync)

---

compose/common.env
compose/development.yml
compose/docker-compose-common.yml
compose/docker-compose.yml

Also add some common.env variables that drive NTP and FWD_IP

Add the FORWARDER that does port forwarding for the docker services

---

add-from-ssh.sh
run-in-mac.sh
run-in-packet.sh
run-in-system.sh
scripts/join_rebar.sh
scripts/ssh-copy-id.sh

driven by the run-in-system.sh and add-from-ssh.sh scripts.
Also, move the run-in-hosts file to tmp and have multiple of them.
This way multiple things can be run at once.

Add/Update the ssh-copy-id.sh script to work better and be

---

run-in-packet.sh
tasks/packet_isos.yml

faster packet install by using local mirror w/o adding it to the general install.

use fast local mirror for ISOs

---

.rsync-filter

we moved the directory but did not update the rsync skip instruction

digitalrebar directory moved, do not copy local

---

compose/setup.sh

one day depend upon it include it.

Add docker to setup options and make things that will

---

Vagrantfile
scripts/join_rebar.sh

Add destroy hook to delete node from admin node

Update Vagrant to work with virtual box node deployment

---

Vagrantfile

Tweak admin node bring up params to be

---

compose/workload.sh
group_vars/all.yml
run-in-packet.sh
tasks/compose.yml

to reduce risk of commits w/ passwords, use the github .netrc by default.
Also, add flag for specialized behavior for Packet host w/ different IPs tests (this may be a forward mode only item?)

tweaks for Packet including using .netrc and correct IP for final check

---

compose/common.env

To reset without rebuilding container.

Move Sledgehammer hash and URL to env variables.

---

compose/config-dir/api/config/services/chef-server.json
compose/config-dir/api/config/services/network-server.json

services node.  This is automatic now as part of the system
bring-up

Don't add chef-server.json and network-server.json to the

---

Vagrantfile

linux models and forwarder examples

Allow for twenty nodes and give examples for

---

workloads/wl-init.sh

this was preventing script from working

needs to be o not O to create rebar file

---

scripts/join_rebar.sh
workloads/wl-lib.sh

Relies on https://github.com/digitalrebar/core/pull/967, and should be pulled with it.

Switch from variant to provider where needed to align with core

---

group_vars/all.yml
run-in-packet.sh
tasks/compose.yml
workloads/wl-lib.sh

Fix a missing local test.  Only set vars if unset.

Use netrc based upon if the file is there or not.

---

workloads/wl-lib.sh

for --wl-ceph or --wl-ceph=true

Fix workload and container processing to work

---

tasks/compose.yml

Make sure we reference digitalrebar dir in the correct spot.

Make sure that ssh dir exists

---

workloads/wl-init.sh

Ansible needs epel

---

tasks/base-debian-7.yml
tasks/base-debian-8.yml
tasks/base.yml

Try to add debian support because it is easy to test and gives

---

compose/init_files.sh

Protect against multiple lines

---

tasks/base-centos.yml

all I want to deal with right now.

Purge iptables at the start.  This is not cool, but

---

run-in-packet.sh

minor correction, but = is required instead of space in the hint

fix hint to use =

---

compose/docker-compose-common.yml
compose/init_files.sh
compose/setup.sh
compose/yaml_templates/ux.yml
group_vars/all.yml
run-in-system.sh
workloads/wl-lib.sh

To run, you need both the --con-ux and --wl-ux flags.

Add UX container support.

---

workloads/kubernetes.sh

Change from minion to node

---

workloads/wl-init.sh
workloads/wl-lib.sh

Make ADMIN_IP optional during running admin node
validation.

Make sure ubuntu systems have python-netaddr

---

tasks/compose.yml

YIKES  missing :!

---

Vagrantfile

Pass CIDR into rebar join.  add-from-* scripts should work

---

containers/rebuild-containers

Instead of looking for local uncommitted changes, look for any changes
since last-built-image-id was last changed.

Update container_is_up_to_date to be smarter.

---

containers/fogwrap/fogwrap/api.rb
workloads/kubernetes.sh
workloads/os.map
workloads/wl-lib.sh

Add new os.map for instance image maps
Change the default amazon instance to t2.micro to work with
more images.

Add name fields to gce and amazon to identify hosts

---

run-in-aws.sh
run-in-google.sh
run-in-system.sh
scripts/ssh-copy-id.sh
workloads/wl-init.sh
workloads/wl-lib.sh

Add run-in-google and run-in-aws scripts.

---

workloads/add-provider.sh
workloads/admin-node.sh
workloads/docker-swarm.sh
workloads/kubernetes.sh

front the run-in-... scripts.  Those should be removed or
moved one day.
Add a add-provider.sh script that adds the provider to the system
Update kub and docker-swarm work loads to have a wait on converge
option.

Create a simple admin node create script that can

---

workloads/add-machine.sh
workloads/wl-lib.sh

the specified provider or join a node through
the system provider.

Add an add-machine command to create a node through

---

tasks/compose.yml

ran on a system that actually hit the version test.
this fixes it

fix version syntax

---

run-in-aws.sh

need AWS bigger size, tag name

---

run-in-aws.sh

Also login should work as root from this user, if not
we have another problem  Like the ansible playbook didn't run.

Set the tag as the hostname of the new admin

---

compose/init_files.sh
run-in-system.sh

script was not finding ip.  this addresses the issue/

Address issue w/ IP not on path

---

containers/provisioner/Dockerfile
containers/provisioner/entrypoint.d/40-get-sledgehammer.sh
containers/provisioner/entrypoint.d/42-start-services.sh
containers/provisioner/entrypoint.d/50-find-supported-operating-systems.sh
containers/provisioner/entrypoint.d/50-fix-gemsite.sh
containers/provisioner/update-nodes/backends.go
containers/provisioner/update-nodes/bootenv.go
containers/provisioner/update-nodes/common_ops.go
containers/provisioner/update-nodes/error.go
containers/provisioner/update-nodes/main.go
containers/provisioner/update-nodes/nodes.go
containers/provisioner/update-nodes/templates.go

Here for code review and testing -- it needs HTTPS support along with some initial bootstrapping (crafting proper bootenvs and such) before it can replace the provisioner-database role.

Add initial replacement for provisioner database

---

workloads/kubernetes.sh

Add opencontrail private

---

Vagrantfile

trying to make failure more friendly

add rescue to give user better feedback if rebar CLI fails

---

workloads/docker-swarm.sh

I always look this up at the end of the run, so let's put it here.

add docker hint at to help user test swarm

---

compose/common.env
containers/dns/dns-mgmt.conf
containers/dns/entrypoint.d/50-register-and-start-bind.sh

- configure powerdns and nsupdate from common.env
- turn off bind if bind isn't used.

Allow for different configurations of DNS.

---

run-in-docean.sh

tweak to correct IP detection

---

run-in-system.sh
tasks/base-centos.yml
tasks/base-debian-7.yml
tasks/base-debian-8.yml
tasks/base-ubuntu1404.yml
tasks/base-ubuntu1510.yml
tasks/base.yml
tasks/compose.yml
workloads/docker-swarm.sh

Fix a bug and add help for swarm

Provider Flag Bug & Swarm IP

---

.dr_info.example

helpful to have a reference copy of the dr_info file

add reference example for dr_info

---

tasks/base-centos.yml
tasks/base-debian-7.yml
tasks/base-debian-8.yml
tasks/base-ubuntu1404.yml
tasks/base-ubuntu1510.yml
tasks/compose.yml
tasks/docker-linux.yml
tasks/packet_isos.yml

if python is too old.  Make sure python is at the latest
level for the OS.

Docker updated its system and curl/get_url won't work

---

run-in-google.sh
tasks/base-ubuntu1404.yml

It is easier to update python.
Update python on ubuntu1404 to one that works.

Switch google admin over to ubuntu-14-04 like our other systems.

---

workloads/kubernetes.sh

Helpful output at the end of the run will tell users where the master is.

Add Master Location Kube Hint

---

run-in-google.sh
scripts/wait_for_rebar.sh
tasks/compose.yml

Update google commands with proper syntax to fix ssh issue

Add wait_for_rebar script that waits correctly.

---

.dr_info.example
Vagrantfile

There is an SSH cert issue - I'm pushing this so that others can try and see if it works for them
The goal is to provide a consistent base for running the workload/foo scripts
I've added some typical flags into the example dr_info in the hope that if someone starts with that, then they don't need as many extra flags.

vagrant script to create a client for Windoz users WIP

---

containers/base/docker-entrypoint.sh

Don't assume eth0.  The DHCP container in host mode

---

compose/workload.sh
compose/yaml_templates/base.yml
compose/yaml_templates/provisioner.yml

Make sure we don't fail if we can change to the tag tree in the checked
out pieces.

Expose the needed ports for the provisioner and dns-mgmt for HOST mode

---

containers/provisioner/start-up.sh

IPs.  This includes IPv4 and IPv6 address.  Only use
the default route from the admin network found.
The system will add additional networks later.
This fixes the case where all network IPs assigned to
the node will get added to the boot interface if
we reboot in sledgehammer.

Make the sledgehammer startup only get admin network

---

run-in-google.sh
workloads/wl-lib.sh

are using the correct project instead of default

Add project id to gcloud commands to make sure we

---

tools/rebar-wipe.sh

This could be slower, but makes sure we get all disks.

If raid controller, raid0 everything and parallel wipe.

---

containers/cloudwrap/cloudwrap/openstack.rb
containers/cloudwrap/cloudwrap/waiter.rb

Follow-up to #309 pull that allows the code to handle public/private networks that are not named "public" and "private"
This list will continue to evolve but this provides a start based on what we've seen.
We do require AT LEAST an identified public network.

make openstack provider smarter about network mapping

---

containers/cloudwrap/cloudwrap/openstack.rb

The code was not happy with a provider that defined networks WITHOUT any subnets.  Actually, the code worked fine and the PROVIDER was not happy with systems using those networks.
Anyway - this small change will remove those dead networks.
Also, truncate (only used when debug is off) was not working so I had to change it.

remove bogus networks from results

---

run-in-aws.sh
run-in-google.sh
tasks/base-centos.yml
tasks/base-debian-7.yml
tasks/base-debian-8.yml
tasks/base-ubuntu1404.yml
tasks/base-ubuntu1510.yml
tasks/compose.yml
tasks/packet_isos.yml
workloads/docker-swarm.sh
workloads/kubernetes.sh

for local users, you can include ISOs in digitalrebar/isos and script will push those
fixed missing jq & python-pycurl dependencies
working with scripts, trying to improve experience.

tweaks to improve user notices at end of script

---

tasks/compose.yml

does not find empty case - workaround until I fix detection

need to ignore if no local ISOs

---

tasks/base-centos.yml

update to patch from yesterday adding JQ

EPEL is needed for JQ on Centos

---

run-in-system.sh
scripts/ssh-copy-id.sh

trying to improve defaults and messages based on troubleshooting

minor Tweaks

---

tasks/base.yml

This may prevent issues for users.

add LOW RAM check to prevent running in systems that cannot start rebar

---

Vagrantfile
compose/docker-compose-common.yml
run-in-openstack.sh
workloads/dev-kubernetes.sh
workloads/kubernetes.sh

Adding Vagrant start-up capability for Kubernetes testing
Also, catch config changes from Kargo 1.2 flags.

Kubernetes 1.2 Dev Work

---

Vagrantfile
compose/docker-compose-common.yml
workloads/dev-kubernetes.sh

Continues to make improvements in kubenetes dev environment bring up

Kubernetes Dev Tooling

---

containers/cloudwrap/cloudwrap/openstack.rb

These are small changes that should eventually result in a new Cloudwrap.

OpenStack tuning (does not include new container)

---

containers/rebar-rev-proxy/entrypoint.d/35-start-services.sh

Add a service to rev-proxy to allow forwarder to

---

compose/init_files.sh
run-in-system.sh
tasks/compose.yml
workloads/wl-lib.sh

--classifier=name1:rule-file1.yml
rule file needs to be relative to the compose directory or full path.

Add ability to turn on classifiers with rule files.

---

.gitignore
compose/common.env
compose/docker-compose-common.yml
containers/rebuild-containers
workloads/wl-lib.sh

and push to a tag.
Fix some of the tag pieces.

Add the ability to tag trees when rebuilding containers

---

run-in-aws.sh
scripts/ssh-copy-id.sh

Fix echo issue with backticks.

Make admin node aws disks disappear on termination.

---

workloads/kubernetes.sh

Make sure we add device_id so that we can delete the admin node

---

compose/docker-compose-common.yml
containers/cloudwrap/cloudwrap/api.rb
containers/cloudwrap/cloudwrap/waiter.rb
run-in-system.sh
workloads/kubernetes.sh

change URL to reflect revproxy

---

Vagrantfile

vagrant automation breaks if the endpoint is using localhost instead of an actual IP for the local endpoint
this will tell the user quicklyl

protect vagrant from localhost endpoint

---

compose/docker-compose-common.yml

add comments to compose files to help debugging

debugging comments

---

.gitignore
containers/cloudwrap/cloudwrap/api.rb
containers/rebar-api/Dockerfile

I did NOT include a rebuild the containers on this pull - I'm still testing that and wanted @galthaus to review the changes first.

Cloudwrap to Centos7 and Permissions on Rebar_API

---

workloads/wl-lib.sh

API requests are revproxied to 3000, 
